---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
    env:
      jquery: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress-Core"

ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
- tests/
- vendor/
- acf-json/
- acf-pro/